server:
  port: 8082

spring:
  application:
    name: ms-digitalfix-workorders
  datasource:
    url: jdbc:h2:mem:workorders;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

digitalfix:
  services:
    audit-url: ${AUDIT_URL:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info
